### PR TITLE
[FIX] Unread messages counter

### LINKED ISSUE #190: Unread messages counter is taking into account system messages
image

### PR DESCRIPTION
**Pull request by renatobecker**
Closes #190.

The number of unread messages was counting message types that should not be rendered, such as `livechat_navigation_history`, etc.

### CODE REVIEW

File: src/components/helpers.js [hunk 1]
```diff
@@ -107,9 +107,9 @@ export const createToken = () => (Math.random().toString(36).substring(2, 15) +
 
 export const getAvatarUrl = (username) => (username ? `${ Livechat.client.host }/avatar/${ username }` : null);
 
-export const msgTypesNotDisplayed = ['livechat_video_call', 'livechat_navigation_history', 'au'];
+export const msgTypesNotRendered = ['livechat_video_call', 'livechat_navigation_history', 'au', 'command'];
 
-export const renderMessage = (message = {}) => (message.t !== 'command' && !msgTypesNotDisplayed.includes(message.t));
+export const renderMessage = (message = {}) => (!msgTypesNotRendered.includes(message.t));
```
Comment (tassoevan) [inline src/components/helpers.js]: Please rename it as `canRenderMessage`.
