### PR TITLE
[FIX] Livechat guest avatar using name instead of username

### LINKED ISSUE #369: Wrong avatar displayed (apart from on left sidebar in web app)
I guess this may be related to #237 (and potentially to #368 too) but it's a different issue.

I was just testing my livechat set-up using name 'Testing livechat' but the avatar showing in the chat window on the website was a G instead of a T:

Wrong_avatar

Confusingly when looking at the web client as the agent it was still a G in the main window, but correctly shows as a T in the sidebar:

wrong_avatar_2

Perhaps something to do with the avatar of the closed but still stuck in the left sidebar livechat conversation (as per #368 ) being a chat with a person with a G avatar?

### PR DESCRIPTION
**Pull request by ashwaniYDV**
closes #369

### CODE REVIEW

**Comment by ashwaniYDV** [comment]
@renatobecker 
Do I need to place this `// eslint-disable-next-line no-nested-ternary` in that particular line only or include it in the global settings

**Comment by ashwaniYDV** [comment]
Also do we need to do a check for `name` property too? It is a required filed for a guest to establish communication with agent, so it will always be there. Please suggest

File: src/components/Messages/Message/index.js [hunk 1]
```diff
@@ -88,7 +88,8 @@ export const Message = memo(({
 	>
 		<MessageAvatars
 			avatarResolver={avatarResolver}
-			usernames={compact ? [] : message.u && message.u.username && [message.u.username]}
+			// eslint-disable-next-line no-nested-ternary
+			usernames={compact ? [] : message.alias ? message.u && message.u.name && [message.u.name] : message.u && message.u.username && [message.u.username]}
```
Comment (renatobecker) [inline src/components/Messages/Message/index.js]: I think extending ternary operators is making hard to read the logic. My suggestion is to create a helper method to deal and return the expected `usernames`.

```suggestion
			usernames={this.getMessageUsernames(message)}
```

**Comment by renatobecker** [comment]
> Also do we need to do a check for `name` property too? It is a required filed for a guest to establish communication with agent, so it will always be there. Please suggest

No, the `name` property may not be available, it's possible to disable the registration form.

**Comment by ashwaniYDV** [comment]
> Can you please add a new story to `storybook` representing this use case?
> Thanks.

Sorry @renatobecker I didn't get it. Where should I add the story. I have done the other requested changes.

File: src/components/Messages/Message/index.js [hunk 2]
```diff
@@ -67,6 +67,16 @@ const getSystemMessageText = ({ t, conversationFinishedMessage }) =>
 	|| (t === MESSAGE_TYPE_WELCOME && I18n.t('Welcome'))
 	|| (t === MESSAGE_TYPE_LIVECHAT_CLOSED && (conversationFinishedMessage || I18n.t('Conversation finished')));
 
+const getMessageUsernames = (compact, message) => {
+	if (compact) {
+		return [];
+	}
+	if (message.alias && message.u && message.u.name) {
```
Comment (renatobecker) [inline src/components/Messages/Message/index.js]: Why do check the `alias` property?

**Comment by renatobecker** [comment]
> > Can you please add a new story to `storybook` representing this use case?
> > Thanks.
> 
> Sorry @renatobecker I didn't get it. Where should I add the story? I have done the other requested changes.

Here -> https://github.com/RocketChat/Rocket.Chat.Livechat/blob/develop/src/components/Messages/MessageAvatars/stories.js

File: src/components/Messages/Message/index.js (hunk 2 above)
Comment (ashwaniYDV) [reply src/components/Messages/Message/index.js]: because alias is there only for guest and not for agent

**Comment by ashwaniYDV** [comment]
> > Also do we need to do a check for `name` property too? It is a required filed for a guest to establish communication with agent, so it will always be there. Please suggest
> 
> No, the `name` property may not be available, it's possible to disable the registration form.

So if name property is not there then alias property will also be not there (I guess) and default username will be the avatar.

File: src/components/Messages/Message/index.js (hunk 2 above)
Comment (ashwaniYDV) [reply src/components/Messages/Message/index.js]: Here alias is the possible way to distinguish between guest and agent

Comment (renatobecker) [reply src/components/Messages/Message/index.js]: No. If you check the server-side, the alias is available in other situations.
My suggestion is not to check it.

Comment (ashwaniYDV) [reply src/components/Messages/Message/index.js]: Then how can we distinguish between the guest and agent since name and username properties are common to both. 
Should I check it with regex of `guest-xx` or there is some other way which I don't know? Please help

Comment (renatobecker) [reply src/components/Messages/Message/index.js]: Okay. I'll suggest another implementation.

File: src/components/Messages/Message/index.js [hunk 3]
```diff
@@ -67,6 +67,16 @@ const getSystemMessageText = ({ t, conversationFinishedMessage }) =>
 	|| (t === MESSAGE_TYPE_WELCOME && I18n.t('Welcome'))
 	|| (t === MESSAGE_TYPE_LIVECHAT_CLOSED && (conversationFinishedMessage || I18n.t('Conversation finished')));
 
+const getMessageUsernames = (compact, message) => {
```
Comment (renatobecker) [inline src/components/Messages/Message/index.js]:
```suggestion
const getMessageUsernames = (compact, message) => {
	if (compact || !message.u) {
		return [];
	}
	
	const { alias, u: { username, name} } = message;
	if (alias && name) {
        	return name;
	}
	
	return username;

```

**Comment by ashwaniYDV** [comment]
I have done the chnages @renatobecker. Please review. Also have I added the story corrected?
